name: Hello World
on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: Say Hello
      - uses: echo "Hello from GitHub Actions!"
        with: node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright Tests
        run: npx playwright test
        env:
          BASE_URL: ${{ secrets.BASE_URL }}